skill_alias={
 # Python
    "py": "python",
    "python3": "python",
    "python2": "python",
    "py3": "python",
    "python语言": "python",

    # JavaScript & 前端
    "js": "javascript",
    "javascript": "javascript",
    "ecmascript": "javascript",
    "es6": "javascript",
    "es2015": "javascript",
    "ts": "typescript",
    "typescript": "typescript",

    # Node.js
    "node": "node.js",
    "nodejs": "node.js",
    "node.js": "node.js",
    "node js": "node.js",

    # 前端框架 / 库
    "vue": "vue",
    "vuejs": "vue",
    "vue.js": "vue",
    "react": "react",
    "reactjs": "react",
    "react.js": "react",
    "angular": "angular",
    "angularjs": "angular",
    "angular.js": "angular",
    "jquery": "jquery",
    "j query": "jquery",

    # CSS 相关
    "css": "css",
    "css3": "css",
    "scss": "sass",
    "sass": "sass",
    "less": "less",
    "tailwind": "tailwind css",
    "tailwindcss": "tailwind css",
    "bootstrap": "bootstrap",

    # 后端语言
    "java": "java",
    "c#": "csharp",
    "csharp": "csharp",
    "c++": "cpp",
    "cpp": "cpp",
    "c语言": "c",
    "c ": "c",
    "go": "go",
    "golang": "go",
    "ruby": "ruby",
    "php": "php",
    "rust": "rust",
    "swift": "swift",
    "kotlin": "kotlin",

    # 数据库
    "mysql": "mysql",
    "mysql数据库": "mysql",
    "mysql db": "mysql",
    "postgresql": "postgresql",
    "postgres": "postgresql",
    "pg": "postgresql",
    "mongodb": "mongodb",
    "mongo": "mongodb",
    "redis": "redis",
    "sqlite": "sqlite",
    "oracle": "oracle",
    "sql server": "sqlserver",
    "sqlserver": "sqlserver",
    "mssql": "sqlserver",

    # 数据科学 / AI
    "机器学习": "machine learning",
    "machine learning": "machine learning",
    "ml": "machine learning",
    "深度学习": "deep learning",
    "deep learning": "deep learning",
    "dl": "deep learning",
    "人工智能": "artificial intelligence",
    "ai": "artificial intelligence",
    "数据科学": "data science",
    "data science": "data science",
    "ds": "data science",
    "numpy": "numpy",
    "np": "numpy",
    "pandas": "pandas",
    "pd": "pandas",
    "matplotlib": "matplotlib",
    "tensorflow": "tensorflow",
    "tf": "tensorflow",
    "pytorch": "pytorch",
    "torch": "pytorch",
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",

    # DevOps / 工具
    "git": "git",
    "docker": "docker",
    "kubernetes": "kubernetes",
    "k8s": "kubernetes",
    "linux": "linux",
    "unix": "linux",
    "bash": "bash",
    "shell": "shell",
    "powershell": "powershell",
    "aws": "aws",
    "azure": "azure",
    "gcp": "google cloud",
    "google cloud": "google cloud",
    "ci/cd": "ci/cd",
    "jenkins": "jenkins",

    # 其他常见技能
    "excel": "excel",
    "word": "word",
    "ppt": "powerpoint",
    "powerpoint": "powerpoint",
    "office": "microsoft office",
    "photoshop": "photoshop",
    "ps": "photoshop",
    "figma": "figma",
    "sketch": "sketch",
    "autocad": "autocad",
    "solidworks": "solidworks",
    "blender": "blender",
}